# File: netlify.toml
[[headers]]
  # Apply these headers to all files in the site
  for = "/*"
  [headers.values]
    # Allow requests from any origin (*)
    Access-Control-Allow-Origin = "*"
    # Prevent content type sniffing
    X-Content-Type-Options = "nosniff"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false